// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApyUwfhp-hc-Jrgf5qtPmsneIMBAdCbzk',
    appId: '1:780863620781:web:5869276aa4b6260f94a824',
    messagingSenderId: '780863620781',
    projectId: 'testa-fe959',
    authDomain: 'testa-fe959.firebaseapp.com',
    storageBucket: 'testa-fe959.firebasestorage.app',
    measurementId: 'G-T2PY0KHX3K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCbjKtKRyvltUH2kJnpFY_1kB9HyYfCDg',
    appId: '1:780863620781:android:1b02d8f64c0d321f94a824',
    messagingSenderId: '780863620781',
    projectId: 'testa-fe959',
    storageBucket: 'testa-fe959.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCve_pnuy_Ig0_6x6O-h0mbYxgSu0VoRAY',
    appId: '1:780863620781:ios:c184c67e7a5be14c94a824',
    messagingSenderId: '780863620781',
    projectId: 'testa-fe959',
    storageBucket: 'testa-fe959.firebasestorage.app',
    iosClientId: '780863620781-rrfu41j5ml952q1npu654bdf8dm0ig01.apps.googleusercontent.com',
    iosBundleId: 'com.example.tuan3th',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCve_pnuy_Ig0_6x6O-h0mbYxgSu0VoRAY',
    appId: '1:780863620781:ios:c184c67e7a5be14c94a824',
    messagingSenderId: '780863620781',
    projectId: 'testa-fe959',
    storageBucket: 'testa-fe959.firebasestorage.app',
    iosClientId: '780863620781-rrfu41j5ml952q1npu654bdf8dm0ig01.apps.googleusercontent.com',
    iosBundleId: 'com.example.tuan3th',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApyUwfhp-hc-Jrgf5qtPmsneIMBAdCbzk',
    appId: '1:780863620781:web:6d4f3c988f7c85c494a824',
    messagingSenderId: '780863620781',
    projectId: 'testa-fe959',
    authDomain: 'testa-fe959.firebaseapp.com',
    storageBucket: 'testa-fe959.firebasestorage.app',
    measurementId: 'G-D7H707NM6Q',
  );
}
